/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2012-10-15 13:10:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class workflow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/../foot.jsp", Long.valueOf(1350283935831L));
    _jspx_dependants.put("/admin/../taglib.jsp", Long.valueOf(1345552994159L));
    _jspx_dependants.put("/admin/../top.jsp", Long.valueOf(1350305382989L));
    _jspx_dependants.put("/admin/left.jsp", Long.valueOf(1350298710763L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>流程管理</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/lib-base.jsp\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<div id=\"left\">\r\n");
      out.write("\t<div class=\"innertube\">\r\n");
      out.write("\t\t<h1 class=\"head\">后台管理</h1>\r\n");
      out.write("\t\t<ul class=\"navigation\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"bottom_menu\">\r\n");
      out.write("\t\t\t<ul class=\"navigation\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"../\" class=\"beright\">返回主菜单</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t<div id=\"page\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"head\">\r\n");
      out.write("\t<div class=\"innertube\">\r\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /admin/../top.jsp(4,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user ne NULL}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span><a href=\"");
          out.print(request.getContextPath());
          out.write("/\">首页</a></span>\r\n");
          out.write("\t\t\t<span style=\"float: right;\"> 欢迎您:<font color=\"green\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</font>， \r\n");
          out.write("\t\t\t\t<a href=\"");
          out.print(request.getContextPath());
          out.write("/j_security_logout.html\">退出系统</a> </span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      out.write("\r\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /admin/../top.jsp(9,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user eq NULL}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span> &nbsp; </span>\r\n");
          out.write("\t\t\t<span style=\"float: right;\"> <a href=\"");
          out.print(request.getContextPath());
          out.write("/login.html\">登录</a></span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      out.write("\r\n");
      out.write("\t\t<hr style=\"clear: both;\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"main\">\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\t\t\t\t\tvar t = null;\r\n");
      out.write("\t\t\t\t\tvar nodeTable = null;\r\n");
      out.write("\t\t\t\t\tvar userTable = null;\r\n");
      out.write("\t\t\t\t\tvar currentWorkflowId = null;\r\n");
      out.write("\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t\tt = new SimpleTable(\"workflowQueryTable\", {\r\n");
      out.write("\t\t\t\t\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\t\t\t\t\tparam : 'searchDiv',\r\n");
      out.write("\t\t\t\t\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/workflow/query.html',\r\n");
      out.write("\t\t\t\t\t\t\tsortables : [\"name\"],\r\n");
      out.write("\t\t\t\t\t\t\tpagingOptions : {\r\n");
      out.write("\t\t\t\t\t\t\t\tfirst : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tend : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tgo : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tfirstHtml : '<a href=\"#\">首页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tlastHtml : '<a href=\"#\">上一页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tnextHtml : '<a href=\"#\">下一页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tendHtml : '<a href=\"#\">尾页</a>'\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t//checkMode : 'single',\r\n");
      out.write("\t\t\t\t\t\t\t// scrollX : true,\r\n");
      out.write("\t\t\t\t\t\t\tcolumns : {\r\n");
      out.write("\t\t\t\t\t\t\t\tname : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '流程名称',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '44%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tcode : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '流程代码',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '30%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tops : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '操作',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '28%'\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tformatters : {\r\n");
      out.write("\t\t\t\t\t\t\t\tops : function(v, obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar html = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml += \"<a href='javascript:doEdit(\" + obj.id + \");'>修改</a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml += \"&nbsp;&nbsp;<a href='javascript:managerNode(\" + obj.id + \");'>管理节点</a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml += \"&nbsp;&nbsp;<a href='javascript:doDelete(\" + obj.id + \");'>删除</a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn html;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tinfo : {\r\n");
      out.write("\t\t\t\t\t\t\t\t//pageSizeSelect:'', //不显示此控件\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSizeSelect : '显示{0}条记录',\r\n");
      out.write("\t\t\t\t\t\t\t\tpagingInfo : '目前显示{0}-{1}条记录，共计：{2}'\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tnodeTable = new SimpleTable(\"nodeQueryTable\", {\r\n");
      out.write("\t\t\t\t\t\t\tpageSize : 8,\r\n");
      out.write("\t\t\t\t\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\t\t\t\t\tparam : 'searchNodeDiv',\r\n");
      out.write("\t\t\t\t\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/workflow/node/query.html',\r\n");
      out.write("\t\t\t\t\t\t\t//sortables : [\"name\"],\r\n");
      out.write("\t\t\t\t\t\t\tpagingOptions : {\r\n");
      out.write("\t\t\t\t\t\t\t\tfirst : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tend : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tgo : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tfirstHtml : '<a href=\"#\">首页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tlastHtml : '<a href=\"#\">上一页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tnextHtml : '<a href=\"#\">下一页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tendHtml : '<a href=\"#\">尾页</a>'\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t//checkMode : 'single',\r\n");
      out.write("\t\t\t\t\t\t\t// scrollX : true,\r\n");
      out.write("\t\t\t\t\t\t\tcolumns : {\r\n");
      out.write("\t\t\t\t\t\t\t\trownum : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '序号',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '5%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tname : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '节点名称',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '18%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tyNodeName : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : 'Y节点',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '18%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tnNodeName : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : 'N节点',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '18%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tstartPoint : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : \"起点\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '6%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tendPoint : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : \"终点\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '6%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tuserName : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : \"所属用户\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '15%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tops : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '操作',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '12%'\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tformatters : {\r\n");
      out.write("\t\t\t\t\t\t\t\tstartPoint : function(v, obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn v ? '是' : \"否\";\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tendPoint : function(v, obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn v ? '是' : \"否\";\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tops : function(v, obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar html = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml += \"<a href='javascript:doEditNode(\" + obj.id + \");'>修改</a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml += \"&nbsp;&nbsp;<a href='javascript:doDeleteNode(\" + obj.id + \");'>删除</a>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn html;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tinfo : {\r\n");
      out.write("\t\t\t\t\t\t\t\t//pageSizeSelect:'', //不显示此控件\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSizeSelect : '显示{0}条记录',\r\n");
      out.write("\t\t\t\t\t\t\t\tpagingInfo : '目前显示{0}-{1}条记录，共计：{2}'\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tuserTable = new SimpleTable(\"userQueryTable\", {\r\n");
      out.write("\t\t\t\t\t\t\tpageSize : 5,\r\n");
      out.write("\t\t\t\t\t\t\tautoLoad : false,\r\n");
      out.write("\t\t\t\t\t\t\tparam : 'searchUserDiv',\r\n");
      out.write("\t\t\t\t\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/admin/user_query.ajax',\r\n");
      out.write("\t\t\t\t\t\t\tpagingOptions : {\r\n");
      out.write("\t\t\t\t\t\t\t\tfirst : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tend : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tgo : true,\r\n");
      out.write("\t\t\t\t\t\t\t\tfirstHtml : '<a href=\"#\">首页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tlastHtml : '<a href=\"#\">上一页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tnextHtml : '<a href=\"#\">下一页</a>',\r\n");
      out.write("\t\t\t\t\t\t\t\tendHtml : '<a href=\"#\">尾页</a>'\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tcheckMode : 'single',\r\n");
      out.write("\t\t\t\t\t\t\t// scrollX : true,\r\n");
      out.write("\t\t\t\t\t\t\tcolumns : {\r\n");
      out.write("\t\t\t\t\t\t\t\tcheckbox : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '5%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tuserName : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '用户名称',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '40%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\troleName : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '用户角色',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '40%'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tdisabled : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\theader : '是否禁用',\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth : '15%'\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tformatters : {\r\n");
      out.write("\t\t\t\t\t\t\t\tdisabled : function(v, obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(v) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '<font color=\"red\">已禁用</font>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn '<font color=\"green\">未禁用</font>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tinfo : {\r\n");
      out.write("\t\t\t\t\t\t\t\t//pageSizeSelect:'', //不显示此控件\r\n");
      out.write("\t\t\t\t\t\t\t\tpageSizeSelect : '显示{0}条记录',\r\n");
      out.write("\t\t\t\t\t\t\t\tpagingInfo : '目前显示{0}-{1}条记录，共计：{2}'\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$('#selectUserDiv').dialog({\r\n");
      out.write("\t\t\t\t\t\t\tdraggable : true,\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '选择用户',\r\n");
      out.write("\t\t\t\t\t\t\twidth : 690,\r\n");
      out.write("\t\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\t\t// position:'center', 'left', 'right', 'top', 'bottom'.  or [350,100]\r\n");
      out.write("\t\t\t\t\t\t\tresizable : false,\r\n");
      out.write("\t\t\t\t\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\t\t\t\t\t// show:'slide',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"OK\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar selectedObj = userTable.getSelectedObj();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(selectedObj.length <= 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectedUserId\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectedUserName\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar selectedUserId = selectedObj[0].id;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar selectedUserName = selectedObj[0].userName;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectedUserId\").val(selectedUserId);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectedUserName\").val(selectedUserName);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\"Cancel\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$('#workflow_add_form_div').dialog({\r\n");
      out.write("\t\t\t\t\t\t\tdraggable : true,\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '添加/修改流程',\r\n");
      out.write("\t\t\t\t\t\t\twidth : 620,\r\n");
      out.write("\t\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\t\t// position:'center', 'left', 'right', 'top', 'bottom'.  or [350,100]\r\n");
      out.write("\t\t\t\t\t\t\tresizable : false,\r\n");
      out.write("\t\t\t\t\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\t\t\t\t\t// show:'slide',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"OK\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tajaxSubmitForm(\"workflow_add_form\", editCallback);\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\"Cancel\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$('#node_manager_div').dialog({\r\n");
      out.write("\t\t\t\t\t\t\tdraggable : true,\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '节点管理',\r\n");
      out.write("\t\t\t\t\t\t\twidth : 800,\r\n");
      out.write("\t\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\t\t// position:'center', 'left', 'right', 'top', 'bottom'.  or [350,100]\r\n");
      out.write("\t\t\t\t\t\t\tresizable : false,\r\n");
      out.write("\t\t\t\t\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\t\t\t\t\t// show:'slide',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"完成\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$('#node_add_form_div').dialog({\r\n");
      out.write("\t\t\t\t\t\t\tdraggable : true,\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '添加/编辑节点',\r\n");
      out.write("\t\t\t\t\t\t\twidth : 620,\r\n");
      out.write("\t\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\t\t// position:'center', 'left', 'right', 'top', 'bottom'.  or [350,100]\r\n");
      out.write("\t\t\t\t\t\t\tresizable : false,\r\n");
      out.write("\t\t\t\t\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\t\t\t\t\t// show:'slide',\r\n");
      out.write("\t\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"OK\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tajaxSubmitForm(\"node_add_form\", function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tnodeTable.doSearch();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\"Cancel\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tfunction editCallback() {\r\n");
      out.write("\t\t\t\t\t\tt.doSearch();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction doEdit(id) {\r\n");
      out.write("\t\t\t\t\t\tdoGetAjax(\"");
      out.print(request.getContextPath());
      out.write("/workflow/workflow/\" + id + \".html\", '', function(data, textStatus, XMLHttpRequest) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#workflow_add_form\")[0].reset();\r\n");
      out.write("\t\t\t\t\t\t\tfillForm(\"workflow_add_form\", data);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#workflow_add_form_div\").dialog(\"open\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction doDelete(id) {\r\n");
      out.write("\t\t\t\t\t\tshowConfirm(\"确认要删除该流程吗？\", function() {\r\n");
      out.write("\t\t\t\t\t\t\tdoPostAjax(\"");
      out.print(request.getContextPath());
      out.write("/workflow/workflow/delete.html\", \"id=\" + id, function(resp) {\r\n");
      out.write("\t\t\t\t\t\t\t\tshowMsg(resp);\r\n");
      out.write("\t\t\t\t\t\t\t\tt.doSearch();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction doEditNode(id) {\r\n");
      out.write("\t\t\t\t\t\tdoGetAjax(\"");
      out.print(request.getContextPath());
      out.write("/workflow/node/\" + id + \".html\", '', function(data, textStatus, XMLHttpRequest) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#node_add_form\")[0].reset();\r\n");
      out.write("\t\t\t\t\t\t\tfillForm(\"node_add_form\", data);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#node_add_form_div\").dialog(\"open\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction doDeleteNode(id) {\r\n");
      out.write("\t\t\t\t\t\tshowConfirm(\"确认要删除该节点吗？\", function() {\r\n");
      out.write("\t\t\t\t\t\t\tdoPostAjax(\"");
      out.print(request.getContextPath());
      out.write("/workflow/node/delete.html\", \"id=\" + id, function(resp) {\r\n");
      out.write("\t\t\t\t\t\t\t\tshowMsg(resp);\r\n");
      out.write("\t\t\t\t\t\t\t\tnodeTable.doSearch();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction managerNode(id) {\r\n");
      out.write("\t\t\t\t\t\tcurrentWorkflowId = id;\r\n");
      out.write("\t\t\t\t\t\t$(\"#f_workflowId\").val(id);\r\n");
      out.write("\t\t\t\t\t\t//yNode和nNode下拉框的param\r\n");
      out.write("\t\t\t\t\t\t$(\"#yNodeSelector\").attr('param', 'workflowId=' + id);\r\n");
      out.write("\t\t\t\t\t\t$(\"#nNodeSelector\").attr('param', 'workflowId=' + id);\r\n");
      out.write("\t\t\t\t\t\tnodeTable.doSearch();\r\n");
      out.write("\t\t\t\t\t\t$(\"#node_manager_div\").dialog(\"open\");\r\n");
      out.write("\t\t\t\t\t\tloadSelector($(\"#yNodeSelector\"));\r\n");
      out.write("\t\t\t\t\t\tloadSelector($(\"#nNodeSelector\"));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction resetNodeAddForm() {\r\n");
      out.write("\t\t\t\t\t\tvar form = $(\"#node_add_form\");\r\n");
      out.write("\t\t\t\t\t\tform[0].reset();\r\n");
      out.write("\t\t\t\t\t\t$(\"#selectedUserId\", form).val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#selectedUserName\", form).val(\"\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<div id=\"searchDiv\" style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\">流程名称：</td><td width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"name\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\">流程代码：</td><td width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"code\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"searchButton\" value=\"查询\" />\r\n");
      out.write("\t\t\t\t\t<script type='text/javascript'>\r\n");
      out.write("\t\t\t\t\t\t$(\"#searchButton\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\tt.doSearch();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\tfunction showAddForm() {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.forms['workflow_add_form'].reset();\r\n");
      out.write("\t\t\t\t\t\t\tvar dialog = $('#workflow_add_form_div').dialog(\"open\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:showAddForm();\">添加新流程</a>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"tableDiv\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t<table id=\"workflowQueryTable\"></table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"workflow_add_form_div\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"workflow_add_form\" action=\"");
      out.print(request.getContextPath());
      out.write("/workflow/edit.html\"  method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display: none;\" name=\"id\" />\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>流程名称：</td><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>流程代码：</td><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"code\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"node_manager_div\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"searchNodeDiv\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"f_workflowId\" name=\"workflowId\" />\r\n");
      out.write("\t\t\t\t\t\t节点名称：\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"searchNoteButton\" value=\"查询\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"showAddNodeForm()\" value=\"添加节点\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t<script type='text/javascript'>\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#searchNoteButton\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tnodeTable.doSearch();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction showAddNodeForm() {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.forms['node_add_form'].reset();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#node_add_form input[name='workflowId']\").val(currentWorkflowId);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dialog = $('#node_add_form_div').dialog(\"open\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"nodeTableDiv\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"nodeQueryTable\"></table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"node_add_form_div\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"node_add_form\" action=\"");
      out.print(request.getContextPath());
      out.write("/workflow/node/edit.html\"  method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display: none;\" name=\"id\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display:none;\" name=\"workflowId\" />\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>节点名称：</td><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" size=\"10\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td> 所属用户： </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userName\" id=\"selectedUserName\" readonly=\"readonly\" size=\"10\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"userId\" id=\"selectedUserId\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"选择\" id=\"selectUserBtn\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"清除\" id=\"clearUserBtn\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#selectUserBtn\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectUserDiv\").dialog(\"open\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#clearUserBtn\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectedUserId\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#selectedUserName\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</script></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Y节点：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"yNodeSelector\" name=\"yNodeId\" class=\"ajaxSelect\" autoLoad=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\tajaxUrl=\"");
      out.print(request.getContextPath());
      out.write("/workflow/node/list.html\" dataRoot=\"nodes\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalueField=\"id\" displayField=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">无</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>N节点：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"nNodeSelector\" name=\"nNodeId\" class=\"ajaxSelect\" autoLoad=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\tajaxUrl=\"");
      out.print(request.getContextPath());
      out.write("/workflow/node/list.html\" dataRoot=\"nodes\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalueField=\"id\" displayField=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">无</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>是否起始节点：</td><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"startPointY\" type=\"radio\" value=\"true\" name=\"startPoint\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"startPointY\">是</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"startPointN\" checked=\"checked\" value=\"false\" type=\"radio\" name=\"startPoint\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"startPointN\">否</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>是否终止节点：</td><td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"endPointY\" type=\"radio\" value=\"true\" name=\"endPoint\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"endPointY\">是</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"endPointN\" checked=\"checked\" value=\"false\" type=\"radio\" name=\"endPoint\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"endPointN\">否</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"selectUserDiv\">\r\n");
      out.write("\t\t\t\t\t<div id=\"searchUserDiv\" style=\"width: 90%;\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"20%\">用户名称：</td><td width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"userName\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"20%\">用户角色：</td><td width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"roleId\" class=\"ajaxSelect\" autoLoad=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\tajaxUrl=\"");
      out.print(request.getContextPath());
      out.write("/admin/user/role_list.ajax\" dataRoot=\"roles\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalueField=\"id\" displayField=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">所有</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"searchUserButton\" value=\"查询\" />\r\n");
      out.write("\t\t\t\t\t\t<script type='text/javascript'>\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#searchUserButton\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tuserTable.doSearch();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"userTableDiv\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"userQueryTable\"></table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"foot\" class=\"noprint\">\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t© Copyright 2012 Hymer. All Rights Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /admin/left.jsp(6,3) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menus}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /admin/left.jsp(6,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /admin/left.jsp(7,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.level eq 2}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /admin/left.jsp(8,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(menu.link, \"/admin/\")}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<li>\r\n");
        out.write("\t\t\t\t\t\t\t<a class='");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(pageContext.request.requestURI eq menu.link) ? \"currentPage\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("' href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</a>\r\n");
        out.write("\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
