/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2012-10-21 09:41:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.hymer.contract.entity.Contract;
import com.hymer.finacing.entity.*;
import com.hymer.core.util.*;

public final class finacing_005fsales_005fmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/foot.jsp", Long.valueOf(1350283935831L));
    _jspx_dependants.put("/taglib.jsp", Long.valueOf(1345552994159L));
    _jspx_dependants.put("/top.jsp", Long.valueOf(1350305382989L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>销售财务管理</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/lib-base.jsp\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$(\"input.dateField\").datepicker({\r\n");
      out.write("\t\t\t\t\tdateFormat : \"yy-mm-dd\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('#payment_edit_form_div').dialog({\r\n");
      out.write("\t\t\t\t\ttitle : '添加/修改',\r\n");
      out.write("\t\t\t\t\tdraggable : true,\r\n");
      out.write("\t\t\t\t\twidth : 420,\r\n");
      out.write("\t\t\t\t\theight : \"auto\",\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t// position:'center', 'left', 'right', 'top', 'bottom'.  or [350,100]\r\n");
      out.write("\t\t\t\t\tresizable : false,\r\n");
      out.write("\t\t\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\t\t\t// show:'slide',\r\n");
      out.write("\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\"OK\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\tajaxSubmitForm(\"payment_edit_form\", function() {\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\"Cancel\" : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tfunction addPayment(isRefund) {\r\n");
      out.write("\t\t\t\tdocument.forms['payment_edit_form'].reset();\r\n");
      out.write("\t\t\t\tvar refund = false;\r\n");
      out.write("\t\t\t\tif (isRefund == \"Y\") {\r\n");
      out.write("\t\t\t\t\trefund = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfillForm(\"payment_edit_form\", {\r\n");
      out.write("\t\t\t\t\tfinacingId : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\t\t\trefund : refund\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#payment_edit_form_div\").dialog(\"open\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction editPayment(id, amount, dealDate, remarks, refund) {\r\n");
      out.write("\t\t\t\tdocument.forms['payment_edit_form'].reset();\r\n");
      out.write("\t\t\t\tfillForm(\"payment_edit_form\", {\r\n");
      out.write("\t\t\t\t\tid : id,\r\n");
      out.write("\t\t\t\t\tamount : amount,\r\n");
      out.write("\t\t\t\t\tdealDate : dealDate,\r\n");
      out.write("\t\t\t\t\trefund : refund,\r\n");
      out.write("\t\t\t\t\tremarks : remarks\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#payment_edit_form_div\").dialog(\"open\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction removePayment(id) {\r\n");
      out.write("\t\t\t\tif(id) {\r\n");
      out.write("\t\t\t\t\tshowConfirm(\"确认要删除吗？\", function() {\r\n");
      out.write("\t\t\t\t\t\tdoPostAjax(\"");
      out.print(request.getContextPath());
      out.write("/finacing/payment/delete.html\", \"id=\" + id, function(resp) {\r\n");
      out.write("\t\t\t\t\t\t\tshowMsg(resp);\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div id=\"left\">\r\n");
      out.write("\t\t\t<div class=\"innertube\">\r\n");
      out.write("\t\t\t\t<h1 class=\"head\">销售财务管理</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"page\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"head\">\r\n");
      out.write("\t<div class=\"innertube\">\r\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /top.jsp(4,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user ne NULL}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span><a href=\"");
          out.print(request.getContextPath());
          out.write("/\">首页</a></span>\r\n");
          out.write("\t\t\t<span style=\"float: right;\"> 欢迎您:<font color=\"green\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</font>， \r\n");
          out.write("\t\t\t\t<a href=\"");
          out.print(request.getContextPath());
          out.write("/j_security_logout.html\">退出系统</a> </span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      out.write("\r\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /top.jsp(9,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user eq NULL}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<span> &nbsp; </span>\r\n");
          out.write("\t\t\t<span style=\"float: right;\"> <a href=\"");
          out.print(request.getContextPath());
          out.write("/login.html\">登录</a></span>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      out.write("\r\n");
      out.write("\t\t<hr style=\"clear: both;\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"main\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t客户信息：\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>客户名称：</label>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.customer.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>地址：</label>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.customer.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>联系人：</label>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.customer.linkman}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>手机：</label>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.customer.mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>电话/传真：</label>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.customer.fax}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<label>邮箱：</label>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.customer.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t合同列表：\r\n");
      out.write("\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"contract_div\">\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" class=\"borders\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>合同编号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>签订时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>合同金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>已收款金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>未收款金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>退款金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										Finacing finacing = (Finacing) request.getAttribute("finacing");
										List<Contract> contracts = (List<Contract>)request.getAttribute("contracts");
										Double contractAmount = 0.0;
										for (int i=0; i<contracts.size(); i++) {
											Contract c = contracts.get(i);
											contractAmount += c.getAmount();
											Date signDate = c.getSignDate();
											String NO = Formatters.formatDate(signDate, "yyyyMMdd");
											if (c.getId() < 10) {
												NO += ("0" + c.getId());
											} else {
												NO += c.getId();
											}
											List<Payment> payments = c.getPayments();
											Double paymentAmount = 0.0;
											Double backAmount = 0.0;
											for (Payment pp : payments) {
												if (pp.isRefund()) {
													backAmount += pp.getAmount();
												} else {
													paymentAmount += pp.getAmount();
												}
											}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(NO);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(Formatters.formatDate(signDate));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(c.getAmount());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><font color=\"green\">");
      out.print(paymentAmount);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print((c.getAmount()-backAmount-paymentAmount));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><font color=\"red\">");
      out.print(backAmount);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												}
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" style=\"text-align: right;\"><b>合同总金额：");
      out.print(contractAmount);
      out.write(" 元（人民币）</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t已收款列表：\r\n");
      out.write("\t\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"javascript:addPayment();\">添加收款信息</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"payment_div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" class=\"borders\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>序号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>合同号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>收款时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>备注</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											List<Payment>payments = finacing.getPayments();
											Double paymentAmount = 0.0;
											for (int i=0; i<payments.size(); i++) {
												Payment p = payments.get(i);
												if (p.isRefund()) {
													continue;
												}
												paymentAmount += p.getAmount();
												
												Contract c = p.getContract();
												Date signDate = c.getSignDate();
												String NO = Formatters.formatDate(signDate, "yyyyMMdd");
												if (c.getId() < 10) {
													NO += ("0" + c.getId());
												} else {
													NO += c.getId();
												}
											
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i+1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(NO);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><font color=\"green\">");
      out.print(p.getAmount());
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(Formatters.formatDate(p.getDealDate()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(p.getRemarks());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href='javascript:editPayment(");
      out.print(p.getId());
      out.write(',');
      out.write(' ');
      out.print(p.getAmount());
      out.write(',');
      out.write(' ');
      out.write('"');
      out.print(Formatters.formatDate(p.getDealDate()));
      out.write("\", \"");
      out.print(p.getRemarks());
      out.write("\");'>修改</a>&nbsp;&nbsp;<a href='javascript:removePayment(");
      out.print(p.getId());
      out.write(");'>删除</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												}
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" style=\"text-align: right;\"><b>已收款总金额：");
      out.print(paymentAmount);
      out.write(" 元（人民币）</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t退款列表：\r\n");
      out.write("\t\t\t\t\t\t\t</legend>\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"javascript:addPayment('Y');\">添加退款信息</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"back_payment_div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\" class=\"borders\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>序号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>合同号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>金额</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>退款时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>备注</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											Double backPaymentAmount = 0.0;
											for (int i=0; i<payments.size(); i++) {
												Payment p = payments.get(i);
												if (p.isRefund()) {
													backPaymentAmount += p.getAmount();
													
													Contract c = p.getContract();
													Date signDate = c.getSignDate();
													String NO = Formatters.formatDate(signDate, "yyyyMMdd");
													if (c.getId() < 10) {
														NO += ("0" + c.getId());
													} else {
														NO += c.getId();
													}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i+1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(NO);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><font color=\"red\">");
      out.print(p.getAmount());
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(Formatters.formatDate(p.getDealDate()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(p.getRemarks());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href='javascript:editPayment(");
      out.print(p.getId());
      out.write(',');
      out.write(' ');
      out.print(p.getAmount());
      out.write(',');
      out.write(' ');
      out.write('"');
      out.print(Formatters.formatDate(p.getDealDate()));
      out.write("\", \"");
      out.print(p.getRemarks());
      out.write('"');
      out.write(',');
      out.write(' ');
      out.print(p.isRefund());
      out.write(");'>修改</a>&nbsp;&nbsp;<a href='javascript:removePayment(");
      out.print(p.getId());
      out.write(");'>删除</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

													}
												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" style=\"text-align: right;\"><b>已退款总金额：");
      out.print(backPaymentAmount);
      out.write(" 元（人民币）</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:window.close();\">关闭本页</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"payment_edit_form_div\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"payment_edit_form\" name=\"payment_edit_form\" action=\"");
      out.print(request.getContextPath());
      out.write("/finacing/payment/edit.html\"  method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display: none;\" name=\"finacingId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display: none;\" name=\"paymentType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${finacing.finacingType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display: none;\" name=\"refund\" value=\"false\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"display: none;\" name=\"id\" />\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"25%\">合同：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"contractId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										for (int i=0; i<contracts.size(); i++) {
											Contract c = contracts.get(i);
											Date signDate = c.getSignDate();
											String NO = Formatters.formatDate(signDate, "yyyyMMdd");
											if (c.getId() < 10) {
												NO += ("0" + c.getId());
											} else {
												NO += c.getId();
											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(c.getId());
      out.write('"');
      out.write('>');
      out.print(NO);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"25%\">金额：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"75%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"amount\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>收款时间：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"dateField\" name=\"dealDate\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>备注：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\t\t\t\t\t\t\t\t<textarea name=\"remarks\" cols=\"30\" rows=\"4\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div id=\"foot\" class=\"noprint\">\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t© Copyright 2012 Hymer. All Rights Reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
